Homepage
rachidelaid/billionaire-appointment-front-end pull request #2
Opened 2022-06-03 13:42 UTC by matovu-farid

## **Homepage**
In this branch, the following changes were added:
- Billionaires were fetched from the billions-back-end 
- The billionaires were displayed on the homepage
- Pagination was added to the homepage to load three billionaires at a time
- The next and back button of the homepage was added
- The homepage was styled

2022-06-03 15:07 UTC, guerreiropedr0 commented on src/pages/Home/index.js
> +        <h2 className={style.subtitle}>Please select a speaker</h2>
[OPTIONAL] This is from the requirements but, it is subject to change. We can discuss this in group meetings which is if it should be "speakers" or "billionaires". But, from now, I think it would be better if we keep billionaires.

Ex:
```
 <h1 className={style.title}>TOP BILLIONAIRES</h1>
 <h2 className={style.subtitle}>Please select a billionaire</h2>
```

2022-06-03 15:09 UTC, guerreiropedr0 commented on src/pages/Home/style.module.css
> +
[OPTIONAL] The design is very well done, congratulations! :tada: 
But we could make it even more spotless if we added some slide effect when displaying different billionaires (right after the click)

Like in the requirements:
_when clicked gives off a slide effect to display more billionaires._

2022-06-03 15:13 UTC, guerreiropedr0 requested changes
Hi @matovu-farid ,

You did extremely great on this project! 👏 👏
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 

## Good Points 👍
- Descriptive Pull Request
- Descriptive commit messages
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

- We need the front-end tests as part of the requirements, kindly add them.

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-06 11:06 UTC, guerreiropedr0 commented on src/components/Billionare/index.js
> +  <div className={style.container}>
I think itt should be possible to click a card and redirect to the details of that billionaire, kindly add this.

2022-06-06 11:07 UTC, guerreiropedr0 commented on src/pages/Home/index.js
> +            </button>
The button still appears when there are no next billionaires, do you think we change this?

2022-06-06 11:09 UTC, guerreiropedr0 commented on src/tests/home.test.js
> +  const home = <Wrapper><Home /></Wrapper>;
One of the tests are failing due to this line, the error message is this:
"Warning: Failed prop type: Invalid prop `children` of type `Object` supplied to `Wrapper`, expected instance of `Array`."

Let's fix the tests!

2022-06-06 11:10 UTC, guerreiropedr0 requested changes
Hi @matovu-farid ,

You did extremely great on this project! 👏 👏
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 

## Good Points 👍
- Descriptive Pull Request
- Descriptive commit messages
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-06 12:27 UTC, matovu-farid commented on src/components/Billionare/index.js
> +  <div className={style.container}>
@guerreiropedr0  This is the homepage branch, it is possible in the details branch however

2022-06-06 12:48 UTC, guerreiropedr0 approved these changes
Hi @matovu-farid 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:


![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions
- Check the single comments :smiley:

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------

2022-06-06 12:52 UTC, merged